spring:
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVICE}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

br.com.fiap.soat7:
  redis-mid-url: ${REDIS_MID_URL}/redis-message/
  upload:
    dir: ${SHARED_DISK}/%s/%s/%s/
server:
  port: 8080
