apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: IMAGE_CORE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            -
              name: REDIS_MID_URL
              value: "http://redis-communication-service"
            -
              name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            -
              name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            -
              name: POSTGRES_SERVICE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-service
            -
              name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
            -
              name: SHARED_DISK
              value: "/opt/app/shared"
          volumeMounts:
            - name: app-storage
              mountPath: "/opt/app/shared"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc